### ISSUE TITLE
`kamilsk/retry` has moved to `octolab/try`

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/packages#1610]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Former cli tool https://github.com/kamilsk/retry

Moved to https://github.com/octolab/try/releases and released by the same author

https://github.com/cloudposse/packages/blob/master/vendor/retry/Makefile

**Comment by Nuru** [comment]
Closing as `invalid` because 
- https://github.com/kamilsk/retry is actively maintained, with latest release Feb 22, 2021, vs https://github.com/octolab/try/releases only has 3 releases, latest one Mar 4, 2019 
- This binary is now easily available with `go get` so we [stopped publishing](https://github.com/cloudposse/packages/blob/9a7de189f6fa4b9f4e26d4933cd19045c50de274/vendor/retry/Makefile#L1-L2) this package as of Nov 22, 2020.
