### ISSUE TITLE
Incorrect packages install for M1/ARM devices

### ISSUE THREAD

**Issue by slewis-bd** [cloudposse/packages#2872]
## Describe the Bug
The variable ARCH does not seem to be set based off the architecture of the system that is calling the command. This results in the incorrect package being installed when on an ARM system.

## Expected Behavior
The proper architecture is detected and the correct package is installed.

## Steps to Reproduce
1. Go to 'arm based system (Apple M1 in my case)'
2. Run 'command to install gomplate'
4. Wrong package is downloaded

## Screenshots
Not a screenshot, but the url that gomplate is downloading from is `https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_darwin-amd64-slim` but should be `https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_darwin-arm64`

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [MacOS]
 - Version: [12.5]
 - Arch: [M1]

**Comment by Nuru** [comment]
This is not so much a bug as a feature request. We do not actually build binaries in all but a few cases. In general, we package binaries that are published as GitHub artifacts by the maintainers. In order for us to package `arm64` packages, the maintainers need to build and publish `arm64` artifacts. They are slow to do this, but even if they do, we want to test packages before releasing them and we have not found a way of running  Linux `arm64` binaries on the GitHub Action Runners at this time. 

We welcome community support in the 2 major chores blocking us:

1. Have a way to run ARM64 Linux on GitHub Action Runners. This is being tracked [here](https://github.com/actions/runner-images/issues/5631). (Even though that issues is focused on building binaries, it is really about having a native ARM64 environment in which to build them, rather than cross-compiling.)
2. Compile and maintain a list of which of our packages have Linux and/or Mac `arm64` binaries available (tracked separately).

Once we have good progress on those fronts, we can enhance our build system to build packages for them.
